### ISSUE TITLE
Problems fixing wifi

### ISSUE THREAD

**Issue by baumph** [duszmox/ThinkPad-X1C4-macOS-OpenCore#1]
Hello, i have got MacOS 12 running on my X1 Yoga. But i don't know how to implement the wifi patch. Can you help me there?

**Comment by duszmox** [comment]
Hi, i will update the repo today around 6-7 pm CEST, it will include the patches required for macos 12

**Comment by baumph** [comment]
I really don't want to stress you in any means. But have you made any progress on this topic?

**Comment by duszmox** [comment]
Hello, sorry for the late response. I wanted to wait for the 0.7.1 release and then it totally went out of my mind, but anyway checkout the [new release](https://github.com/duszmox/ThinkPad-X1C4-macOS-OpenCore/releases/tag/0.7.1), it should solve your problem. if you encounter any errors please let me know.

**Comment by baumph** [comment]
Thank you very much! But i still have a stupid question. How do i add the patch to my config?

**Comment by duszmox** [comment]
Oh yeah sorry, so basically you have to open both plists side by side and than copy the numbered kext entries from the intel-clan plist to the config plist to Kext -> Add. As presented on the picture 
![image](https://user-images.githubusercontent.com/38438001/125106622-1e43fb80-e0e0-11eb-8968-c2e332018c01.png)

**Comment by baumph** [comment]
Thank you very much!!!! I am commenting now on the Hackintosh with fully working wifi. The only thing that doesn't work is the update from Beta 1 to beta 2. But I have the same problem on my genuine MacBook Pro that runs OpenCore legacy. So I am very certain that I can fix it with the USB install.
