### ISSUE TITLE
CPUFriendFriend repo in README no longer exists

### ISSUE THREAD

**Issue by shann93** [duszmox/ThinkPad-X1C4-macOS-OpenCore#2]
Hi,

Under "Custom CPU Power Management" - the github repo  [CPUFriendFriend](https://github.com/fewtarius/CPUFriendFriend) no longer exists. I'm not sure if that was a custom fork or something but this should probably be updated to point elsewhere.

**Comment by duszmox** [comment]
It seems that they moved it to [corpnew](https://github.com/corpnew), thanks for noticing
